### PR TITLE
feat(animation) : Animation fixes and improvements

### LINKED ISSUE #37: Rework integration with the standard GLTF exporter
Currently, the Blender add-on is doing a few shortcuts when it comes to more advanced export settings. (Ie, the standard Blender Gltf exporter has a whole logic in place for example when you toggle animation export on/off), which could lead to bugs/ unexpected behaviour.
There are two main options I see:
 * change the auto exporter to integrate into Blender's Gltf exporter : ie add our custom tabs & settings as additional settings inside the standard exporter (did a few basic attempts at this, and it seems feasible on the surface). This would simplify a part our own code, remove the need to re-implement features etc, but might be complicated to do
 * copy/paste some of the code from the standard exporter's logic & ui  (is an ok stopgap solution, but does not scale at all)

### LINKED ISSUE #131: Default Armature Pose Settings
Hi, changing the pose of my armature I realized the gltf_auto_export plugin doesn't persist these changes in the .glb file.
In blender:
Screenshot 2024-02-17 at 5 52 41 PM

In bevy:
Screenshot 2024-02-17 at 5 54 05 PM

In the normal export gltf 2.0 export panel there's a dedicated Armature menu and there you can choose to use the rest position Armature.

Screenshot 2024-02-17 at 5 55 51 PM

Is there any way to get around this with the current version of the plugin?

Once again, thanks for your time and work into this. This plugin is the reason I took the leap to choose bevy as my game engine of choice!

### LINKED ISSUE #140: Remove "legacy mode" (simplfied component's ron in custom_properties) from both Blender add-on and Bevy side
* [x] remove legacy mode from both ```bevy_gltf_components``` & ```bevy_components```
* [x] "fix"/handle #133

### LINKED ISSUE #145: Repositioning objects doesn't re-export scene
Is there any way to force the export each time instead of checking for changes? I'm encountering an issue where repositioning objects in the scene does not cause the auto export to properly save. Only deleting the `Scene.glb` properly exports the scene.

Screenshot 2024-02-23 at 4 54 49 pm

### LINKED ISSUE #152: Allow filtering which types go into the exported registry
I assume that's what the [`ExportComponentsConfig`](https://docs.rs/bevy_registry_export/latest/bevy_registry_export/struct.ExportComponentsConfig.html) will be for, but all of its members are currently not `pub` and not implemented yet.

What would be useful to me would be to have an allowlist of registered types that will be exported. Most registered types are not relevant for my Blender workflow, but can disrupt my design via name conflicts.
For example, if XPBD's `Collider` ever does into the type registry, we will run into problems with the current recommendation (per the examples) of having an own `Collider` type that is used in Blender.

### LINKED ISSUE #166: Add support for full component paths, to avoid collisions from short_names
Say I have two quests `Foo` and `Bar`. They might both have a component `Objective`, but in order to disambiguate them in the Blender addon, I have to name them `FooObjective` and `BarObjective`. If we instead had some kind of collapsible groupings, I would not have to do this.

### LINKED ISSUE #167: Orphan data Duping (Regression)
Orphan data is created on every save.

## Auto export details
Screenshot 2024-03-07 at 2 04 15 PM

### Orphan data panel (Just purged it)
Screenshot 2024-03-07 at 2 04 41 PM

### Saved once.
Screenshot 2024-03-07 at 2 05 13 PM

### Saved 3 more times
Screenshot 2024-03-07 at 2 05 42 PM

### LINKED ISSUE #175: Add support for animation markers
Blender has them, they can be useful to trigger animations at specific frames etc

### LINKED ISSUE #176: Hashmaps are not displayed
Hashmaps are not being displayed correctly / non editable in Bevy_gltf_components

### LINKED ISSUE #177: Only run auto_export if it is actually enabled

### LINKED ISSUE #178: Change the way change detection is enabled & disabled again
Up until now, change detection was 
* disabled before an export (so that all the changes we make are not registered)
* enabled again **with a one second timer after the call to export**  

Turns out, based on the newly added better change detection tests:
* that they do not get enabled again correctly , at least in cli mode (timer does not run ?)
* but  also very importantly, that the logic behind enabling them again is **WRONG** : it should only happen after the export is REALLY done: so we should switch this to use the post export hooks (glTF2_post_export_callback)!

This could potentially explain the observed semi random weirdness around change detection ! (both it not working for some folks, and running too much for others !)

### LINKED ISSUE #179: Problems with bounding boxes and animation mixing
I've been encountering a weird issue where at certain camera angles portions of the mesh of a blueprinted entity are culled.

Apr-10-2024 19-19-43

Enabling AABB gizmos shows a bunch of bounding boxes floating off in space. 

Screenshot 2024-04-11 at 10 42 51 am

Inspecting the original model, and the one exported from blender show large differences in their reported bounding boxes and the animations from the different models are getting all mixed in together.

Screenshot 2024-04-11 at 10 36 13 am

Screenshot 2024-04-11 at 10 37 47 am

Perhaps I'm doing something catastrophically incorrect with the way I've setup my blender project but I've followed the video guides closely and can't figure out what I'm doing incorrectly.

### LINKED ISSUE #180: Switch to a different approach for change detection
After weeks of experimenting, trying to find workaround for the numerous limitations & issues, I have come to the conclusion that using depsgraph updates to track object changes is too unreliable:

The only solution I see is  "the brute force but hey more reliable" way : By serialising the scenes at every save, and doing a very superficial diffing. 
This way there is 
* no more opaque, unclear rules to how change is detected
* no more forcing depsgraph updates for basic cases (like adding components using bevy_components)
* no more absurd undo/redo behaviour that marks changes all objects in scenes even those who where no part of the undo/redo process
* control what is detected & what not
* it can be expanded upon

### LINKED ISSUE #186: Disabling componenets with checkbox does not properly disable them
Trying to convert marker components into xpbd rigid bodies, and in testing it I noticed that toggling the checkbox does not actually toggle them as expected. With the marker component unchecked it is still compiled into the gltf file.

### PR DESCRIPTION
**Pull request by kaosat-dev**
fixes #167 
fixes #131 
closes #37 
closes #175 
closes #177 
fixes #178 
fixes #180 
fixes #145 
closes #140 
fixes #179 
fixes #176 
fixes #166 
closes #152
fixes #186

### CODE REVIEW

**Comment by slyedoc** [comment]
I have tracked this branch a few times over the last month, just pulled the lastest and the change detection as been wonderful.  Ty

**Comment by kaosat-dev** [comment]
> I have tracked this branch a few times over the last month, just pulled the lastest and the change detection as been wonderful. Plus everything else.

Thanks a lot , the kind words and the testing out of this branch are much appreciated ! Just a few more things and I really hope to be able to release this !

**Comment by slyedoc** [comment]
Just a heads up, I started using this crate about 3 months ago, started to really learn blender then as well, after few months I was kinda fighting blender and your exporter, but didn't know enough to tell which was the issue or it was just me.  Was tracking this branch for a while, but about a month back I started doing my own refactor to understand it better.   I will never be a maintainer, and I am the only intended user, but thought some of it may be useful to you, [bevy_sly_blender](https://github.com/slyedoc/bevy_sly_blender)

**Comment by kaosat-dev** [comment]
> Just a heads up, I started using this crate about 3 months ago, started to really learn blender then as well, after few months I was kinda fighting blender and your exporter, but didn't know enough to tell which was the issue or it was just me. Was tracking this branch for a while, but about a month back I started doing my own refactor to understand it better. I will never be a maintainer, and I am the only intended user, but thought some of it may be useful to you, [bevy_sly_blender](https://github.com/slyedoc/bevy_sly_blender)

Hi ! Sorry it took me ages to get back to you, your fork is actually amazing ! 
There are a lot of things that ended up being similar in Blenvy, but there are quite a few things in your work that I would love to integrate into this repo, for example 
* right click to edit blueprints (this one is amazing for qol !)
* the idea about not needing to pregenerate all the propertyGroups 
* the overall simplification

Btw, in Blenvy, the issue with multiple material slots has been resolved (among other things :) ) 
I am closing this branch as it is deprecated, but keeping an eye on your repo , great work !

**Pull request closed without merging**
